# Generated by Django 6.0.2 on 2026-02-27 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('dia_semana', models.CharField(max_length=15)),
                ('entrada_1', models.TimeField(blank=True, null=True)),
                ('saida_1', models.TimeField(blank=True, null=True)),
                ('entrada_2', models.TimeField(blank=True, null=True)),
                ('saida_2', models.TimeField(blank=True, null=True)),
                ('entrada_3', models.TimeField(blank=True, null=True)),
                ('saida_3', models.TimeField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
            ],
            options={
                'unique_together': {('funcionario', 'data')},
            },
        ),
    ]
