# Generated by Django 6.0.2 on 2026-02-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registroponto'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='editado_manualmente',
            field=models.BooleanField(default=False),
        ),
    ]
