# Generated by Django 6.0.2 on 2026-02-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registroponto_editado_manualmente'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='grupo_ponto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
