# Generated by Django 6.0.2 on 2026-02-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_funcionario_grupo_ponto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PisIgnorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pis', models.CharField(max_length=11, unique=True)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
