# Generated by Django 6.0.2 on 2026-02-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pisignorado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriculaIgnorada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
