# Generated by Django 6.0.2 on 2026-05-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_matriculaignorada'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpfIgnorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_adicionado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
