# Generated by Django 6.0.2 on 2026-05-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cpfignorado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='grupo_ponto',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='core.grupo'),
        ),
    ]
