# Generated by Django 6.0.2 on 2026-03-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b75', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('preco_cartela', models.DecimalField(decimal_places=2, default=2.5, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('active', 'Em Andamento'), ('completed', 'Concluído')], default='pending', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
