# Generated by Django 6.0.2 on 2026-03-04 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b75', '0002_sorteio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_nome', models.CharField(blank=True, max_length=50, null=True)),
                ('dados_json', models.JSONField()),
                ('hash_verificacao', models.CharField(max_length=32, unique=True)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b75.cliente')),
                ('sorteio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartelas', to='b75.sorteio')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroSorteado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('ordem', models.PositiveSmallIntegerField()),
                ('sorteio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numeros_globais', to='b75.sorteio')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('sorteio', 'numero')},
            },
        ),
    ]
