# Generated by Django 6.0.2 on 2026-03-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b75', '0003_cartela_numerosorteado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='comanda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Comanda'),
        ),
    ]
