# Generated by Django 6.0.2 on 2026-03-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b75', '0004_cliente_comanda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('estoque', models.IntegerField(default=0, verbose_name='Quantidade em Estoque')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
