# Generated by Django 6.0.2 on 2026-04-09 17:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b75', '0008_alter_cliente_usuario_alter_pedido_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicencaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início da Licença')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim da Licença')),
                ('ilimitado', models.BooleanField(default=False, verbose_name='Acesso Ilimitado / Vitalício')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='licenca', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
