# Generated by Django 6.0.2 on 2026-04-10 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b75', '0009_licencausuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencausuario',
            name='usuario',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='licenca', to=settings.AUTH_USER_MODEL),
        ),
    ]
